### ISSUE TITLE
List of plugins rather than a site-only list

### ISSUE THREAD

**Issue by hhsnopek** [itsabot/itsabot.org#12]
I've been trying to find all the plugins available at this current time, but at this time there's no way to list all the plugins. I think it would be better to go with just a standard list of plugins that can be added to in this repo via PR, that way we don't have to access the website to search/view all plugins.

**Comment by egtann** [comment]
We should definitely have a way to browse all plugins! I'd be happy to accept a PR that added a link to a new page that offered that functionality, e.g. `/plugins/all`. Although it should pull them from the DB that tracks the plugins (i.e. not be a place for people to list plugins via pull request)

You can also search for plugins and publish them via the CLI. It's undocumented because it's new, but just use `abot plugin search emoji` for example, or `abot p s emoji` for short. To publish, `abot plugin publish gopathhere`

**Comment by hhsnopek** [comment]
I was more so thinking having a markdown file that contained all of them in this repo rather than storing them in a database, which we could then parse/render with all the current search functionality? Additions would just be a PR to the file

**Comment by egtann** [comment]
I understand, but the system's already built, so going back to a text file with manual PRs seems like a step backward. Under the current system we can pretty easily do continuous integration on the plugins and provide feedback to creators without taking up time inspecting PRs.

**Comment by hhsnopek** [comment]
I can see where you're coming from, that's fine 😄
When I get some more free time I'll get this rolling

**Comment by egtann** [comment]
FYI, I updated the site today and added (among many other things) a browse button. https://www.itsabot.org

Closing!

**Comment by hhsnopek** [comment]
cool - what happened to the plugins that were listed there previously?

**Comment by egtann** [comment]
Currently there needs to be an icon to be displayed in the "Popular plugins" section to keep it looking nice / visually interesting. The broken image in there now will be fixed shortly.

You can see all the plugins in the "Browse plugins" section. Any plugins that are missing from that section would be because someone re-published a plugin, but there was an error in our continuous integration testing (i.e. the plugin needs to be able to compile with Abot's master branch, or we don't show it).

Soon I'll provide automatic feedback via email if a change in Abot's core breaks one of your plugins, so you can get it fixed and re-published.
